databases:
  - name: blue-ray-pay
    databaseName: capston_database
    user: peter

services:
  - type: web
    name: blue-ray-pay
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        plan: free
