databases:
  - name: pb-database
    databaseName: pb_database
    user: peter1907

services:
  - type: web
    name: Blue-ray-Pay
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Blue-ray-Pay
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        plan: free
